### ISSUE TITLE
Infinite Kameo Charge Cheat & Special Move Controller Inputs

### ISSUE THREAD

**Issue by orn8** [ermaccer/MK1Hook#13]
There isn't a cheat to have infinite kameo charge. I was playing tutorial earlier and saw that some levels allow you to have infinite kameo, so there may be a way to implement this. Practice mode allows this too.

Also, is it possible to create a series of inputs for controllers to activate a special move? Kind of how it normally works, you do `Down Front A` and it activates a special move on controller.

**Comment by ermaccer** [comment]
1. I don't have access to kameo object and I don't want to do ugly memory hacks when there's a possible way to do it properly.

2. Even If I did that, it'd still require a ton of other checks such as not being hit, air state and much more. Script tab is mostly so that you can check out .MKO stuff or make concept videos. It's not really made so that you can "mod" the game to have extra moves etc.

**Comment by orn8** [comment]
thanks, sorry for the inconvenience.
